# Generated by Django 2.1.2 on 2018-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('human_name', models.CharField(max_length=50)),
                ('data_raw', models.TextField(db_column='data')),
                ('is_active', models.BooleanField(default=0)),
            ],
        ),
    ]
